Zadanie 1

CREATE USER EWA
IDENTIFIED BY ewa
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 100M ON USERS;

Zadanie 2

Grant connect, resource, create view to EWA;

Zadanie 3

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='CONNECT';
SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE='RESOURCE';